In [1]:
import pandas as pd

In [3]:
df=pd.read_csv('Dataset/Sensor_Discrimination.csv')
df

,F2,F3,F1,F11,F4,F6,F10,F9,F5,F7,F12,F8,out
0,2.311,3.179,1.473,1.111,2.666,0.2771,1.138,0.2539,0.2795,0.22340,4.712,0.18550,a
1,2.377,3.214,1.460,1.027,2.920,0.3064,1.213,0.3027,0.2527,0.02563,5.463,0.19650,a
2,2.164,3.064,1.552,1.058,2.745,0.2100,1.221,0.2100,0.2820,0.17210,5.332,0.19290,a
3,2.228,3.149,1.605,1.062,2.834,0.3613,1.144,0.2734,0.2917,0.20870,4.829,0.12940,a
4,2.114,3.309,1.534,1.112,2.976,0.2502,1.254,0.2039,0.2100,0.22580,5.734,0.17700,a
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2207,1.301,4.939,3.682,1.174,4.453,0.7922,1.478,0.3687,0.4895,0.23190,5.125,0.05005,b
2208,1.293,4.949,3.412,1.167,4.199,0.9521,1.526,0.4578,0.4578,0.21360,5.433,0.23070,b
2209,1.284,5.111,3.640,1.118,4.460,0.8020,1.460,0.4309,0.5786,0.26980,4.867,0.31740,b
2210,1.261,5.049,3.746,1.128,4.885,1.1470,1.482,0.4614,0.5835,0.32350,5.627,0.23070,b
2211,1.108,5.422,3.959,1.244,4.835,1.3230,1.595,0.5737,0.5579,0.51510,5.623,0.21000,b

In [5]:
norm_tcolumns = df[df.columns[:-1]]
# norm_tcolumns

In [6]:
from sklearn.preprocessing import MaxAbsScaler


def normalize_data(rawData):
    # training
    norm_tcolumns = rawData[rawData.columns[:9]]  # only the first nine columns need normalization, the rest is binary
    #     scaler = MinMaxScaler(copy=True, feature_range=(0, 1)).fit(norm_tcolumns.values)
    scaler = MaxAbsScaler(copy=True).fit(norm_tcolumns.values)
    scaledf = scaler.transform(norm_tcolumns.values)
    training_examples = pd.DataFrame(scaledf, index=norm_tcolumns.index,
                                     columns=norm_tcolumns.columns)  # scaledf is converted from array to dataframe
    rawData.update(training_examples)

    return rawData

In [7]:
df=normalize_data(df)

In [8]:
df

,F2,F3,F1,F11,F4,F6,F10,F9,F5,F7,F12,F8,out
0,0.494332,0.534825,0.288541,0.196986,0.443373,0.076168,0.214232,0.099141,0.101489,0.22340,4.712,0.18550,a
1,0.508449,0.540713,0.285994,0.182092,0.485615,0.084222,0.228351,0.118196,0.091757,0.02563,5.463,0.19650,a
2,0.462888,0.515478,0.304016,0.187589,0.456511,0.057724,0.229857,0.081999,0.102397,0.17210,5.332,0.19290,a
3,0.476578,0.529778,0.314398,0.188298,0.471312,0.099313,0.215361,0.106755,0.105919,0.20870,4.829,0.12940,a
4,0.452193,0.556696,0.300490,0.197163,0.494928,0.068774,0.236069,0.079617,0.076253,0.22580,5.734,0.17700,a
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2207,0.278289,0.830922,0.721254,0.208156,0.740562,0.217757,0.278238,0.143967,0.177741,0.23190,5.125,0.05005,b
2208,0.276578,0.832604,0.668364,0.206915,0.698320,0.261710,0.287274,0.178758,0.166231,0.21360,5.433,0.23070,b
2209,0.274652,0.859859,0.713026,0.198227,0.741726,0.220451,0.274849,0.168255,0.210094,0.26980,4.867,0.31740,b
2210,0.269733,0.849428,0.733790,0.200000,0.812406,0.315283,0.278991,0.180164,0.211874,0.32350,5.627,0.23070,b
2211,0.237005,0.912180,0.775514,0.220567,0.804091,0.363661,0.300264,0.224014,0.202578,0.51510,5.623,0.21000,b

In [9]:
label=df.iloc[:,-1]
label

0       a
1       a
2       a
3       a
4       a
       ..
2207    b
2208    b
2209    b
2210    b
2211    b
Name: out, Length: 2212, dtype: object

In [16]:
from sklearn.calibration import LabelEncoder


le = LabelEncoder()
le.fit(label)
LabelEncoder()
print('classes are :',list(le.classes_))
encoded_label=le.transform(label)

print(encoded_label)
# >>> list(le.inverse_transform([2, 2, 1]))
# ['tokyo', 'tokyo', 'paris']

classes are : ['a', 'b', 'c']
[0 0 0 ... 1 1 1]

In [23]:
# updating the column  
df.loc[: , 'out'] = encoded_label
  
# writing into the file 
# df.to_csv("AllDetails.csv", index=False) 
  
print(df)

            F2        F3        F1       F11        F4        F6       F10  \
0     0.494332  0.534825  0.288541  0.196986  0.443373  0.076168  0.214232
1     0.508449  0.540713  0.285994  0.182092  0.485615  0.084222  0.228351
2     0.462888  0.515478  0.304016  0.187589  0.456511  0.057724  0.229857
3     0.476578  0.529778  0.314398  0.188298  0.471312  0.099313  0.215361
4     0.452193  0.556696  0.300490  0.197163  0.494928  0.068774  0.236069
...        ...       ...       ...       ...       ...       ...       ...
2207  0.278289  0.830922  0.721254  0.208156  0.740562  0.217757  0.278238
2208  0.276578  0.832604  0.668364  0.206915  0.698320  0.261710  0.287274
2209  0.274652  0.859859  0.713026  0.198227  0.741726  0.220451  0.274849
2210  0.269733  0.849428  0.733790  0.200000  0.812406  0.315283  0.278991
2211  0.237005  0.912180  0.775514  0.220567  0.804091  0.363661  0.300264

            F9        F5       F7    F12       F8 out
0     0.099141  0.101489  0.22340  4.712  0.18550   0
1     0.118196  0.091757  0.02563  5.463  0.19650   0
2     0.081999  0.102397  0.17210  5.332  0.19290   0
3     0.106755  0.105919  0.20870  4.829  0.12940   0
4     0.079617  0.076253  0.22580  5.734  0.17700   0
...        ...       ...      ...    ...      ...  ..
2207  0.143967  0.177741  0.23190  5.125  0.05005   1
2208  0.178758  0.166231  0.21360  5.433  0.23070   1
2209  0.168255  0.210094  0.26980  4.867  0.31740   1
2210  0.180164  0.211874  0.32350  5.627  0.23070   1
2211  0.224014  0.202578  0.51510  5.623  0.21000   1

[2212 rows x 13 columns]

In [24]:
df.to_csv('Sensor_discrimination_normalized.csv', index=False)